-- migrations/1722105006-create_initial_tables.sql
-- :up
-- Up migration

CREATE TABLE author (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE version (
    version BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by UUID REFERENCES author(id)
);

CREATE TABLE entity_type (
    name TEXT PRIMARY KEY,
    has_sequence BOOLEAN NOT NULL DEFAULT FALSE,
    sequence BIGINT NOT NULL DEFAULT 0,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE entity (
    id TEXT NOT NULL,
    entity_type TEXT NOT NULL REFERENCES entity_type(name),
    version BIGINT NOT NULL REFERENCES version(version),
    references_to TEXT[] NOT NULL,
    referenced_by TEXT[] NOT NULL,
    data TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (id, version)
);

INSERT INTO entity_type (name, has_sequence) VALUES
('category', TRUE),
('business_schedule', TRUE),
('calendar', TRUE),
('bank', TRUE),
('contract_template', TRUE),
('term_set_hierarchy', TRUE),
('payment_institution', TRUE),
('provider', TRUE),
('terminal', TRUE),
('inspector', TRUE),
('system_account_set', TRUE),
('external_account_set', TRUE),
('proxy', TRUE),
('cash_register_provider', TRUE),
('routing_rules', TRUE),
('bank_card_category', TRUE),
('criterion', TRUE),
('document_type', TRUE),
('currency', FALSE),
('payment_method', FALSE),
('payout_method', FALSE),
('globals', FALSE),
('payment_service', FALSE),
('payment_system', FALSE),
('payment_token', FALSE),
('mobile_operator', FALSE),
('crypto_currency', FALSE),
('country', FALSE),
('trade_bloc', FALSE),
('identity_provider', FALSE),
('limit_config', FALSE);

CREATE INDEX idx_entity_type ON entity(entity_type);
CREATE INDEX idx_entity_version ON entity(version);

-- :down
-- Down migration

DROP RULE IF EXISTS entity_insert_route ON entity;
DROP INDEX IF EXISTS idx_entity_with_sequence_sequence;
DROP INDEX IF EXISTS idx_entity_version;
DROP INDEX IF EXISTS idx_entity_type;
DROP TABLE IF EXISTS entity;
DROP TABLE IF EXISTS entity_type;
DROP TABLE IF EXISTS version;
DROP TABLE IF EXISTS author;
